import nodemailer from 'nodemailer';

// Email configuration using Gmail SMTP
const createTransporter = () => {
  return nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.SMTP_USER || 'rajeshwaritechservice@gmail.com',
      pass: process.env.SMTP_PASS || process.env.GMAIL_APP_PASSWORD, // App password, not regular password
    },
  });
};

// Send enquiry notification email
export const sendEnquiryNotification = async (enquiryData: {
  name: string;
  email: string;
  phone?: string;
  company?: string;
  service: string;
  message?: string;
  enquiryId: number;
}) => {
  try {
    const transporter = createTransporter();
    
    const mailOptions = {
      from: `"RajeshwariTech" <${process.env.SMTP_USER || 'rajeshwaritechservice@gmail.com'}>`,
      to: 'rajeshwaritechservice@gmail.com',
      subject: `🔔 New Enquiry #${enquiryData.enquiryId} - ${enquiryData.service}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8fafc;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
            <h1 style="color: white; margin: 0; font-size: 24px;">🎉 New Enquiry Received!</h1>
            <p style="color: #e2e8f0; margin: 10px 0 0 0;">RajeshwariTech Contact Form</p>
          </div>
          
          <div style="background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <div style="background: #f1f5f9; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
              <h2 style="color: #1e293b; margin: 0 0 15px 0; font-size: 18px;">📋 Enquiry Details</h2>
              <table style="width: 100%; border-collapse: collapse;">
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #475569; width: 120px;">Enquiry ID:</td>
                  <td style="padding: 8px 0; color: #1e293b;">#${enquiryData.enquiryId}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #475569;">Name:</td>
                  <td style="padding: 8px 0; color: #1e293b;">${enquiryData.name}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #475569;">Email:</td>
                  <td style="padding: 8px 0; color: #1e293b;"><a href="mailto:${enquiryData.email}" style="color: #3b82f6; text-decoration: none;">${enquiryData.email}</a></td>
                </tr>
                ${enquiryData.phone ? `
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #475569;">Phone:</td>
                  <td style="padding: 8px 0; color: #1e293b;"><a href="tel:${enquiryData.phone}" style="color: #3b82f6; text-decoration: none;">${enquiryData.phone}</a></td>
                </tr>
                ` : ''}
                ${enquiryData.company ? `
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #475569;">Company:</td>
                  <td style="padding: 8px 0; color: #1e293b;">${enquiryData.company}</td>
                </tr>
                ` : ''}
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; color: #475569;">Service:</td>
                  <td style="padding: 8px 0; color: #1e293b; background: #dbeafe; padding: 4px 8px; border-radius: 4px; display: inline-block;">${enquiryData.service}</td>
                </tr>
              </table>
            </div>
            
            ${enquiryData.message ? `
            <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
              <h3 style="color: #1e293b; margin: 0 0 10px 0; font-size: 16px;">💬 Message</h3>
              <p style="color: #475569; margin: 0; line-height: 1.6; white-space: pre-wrap;">${enquiryData.message}</p>
            </div>
            ` : ''}
            
            <div style="background: #ecfdf5; padding: 20px; border-radius: 8px; border-left: 4px solid #10b981;">
              <h3 style="color: #065f46; margin: 0 0 10px 0; font-size: 16px;">⚡ Quick Actions</h3>
              <p style="color: #047857; margin: 0 0 10px 0;">Reply directly to this email to respond to the customer.</p>
              <p style="color: #047857; margin: 0; font-size: 14px;">Enquiry received on: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p>
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 20px; color: #64748b; font-size: 12px;">
            <p>This email was automatically generated by RajeshwariTech Contact Form</p>
            <p>Visit: <a href="https://rajeshwaritech.com" style="color: #3b82f6;">rajeshwaritech.com</a></p>
          </div>
        </div>
      `,
    };

    const result = await transporter.sendMail(mailOptions);
    console.log('✅ Enquiry notification email sent:', result.messageId);
    return { success: true, messageId: result.messageId };
    
  } catch (error) {
    console.error('❌ Error sending enquiry notification email:', error);
    return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
  }
};

// Send welcome email to customer
export const sendWelcomeEmail = async (customerData: {
  name: string;
  email: string;
  service: string;
}) => {
  try {
    const transporter = createTransporter();
    
    const mailOptions = {
      from: `"RajeshwariTech" <${process.env.SMTP_USER || 'rajeshwaritechservice@gmail.com'}>`,
      to: customerData.email,
      subject: `Thank you for contacting RajeshwariTech! 🚀`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8fafc;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
            <h1 style="color: white; margin: 0; font-size: 24px;">🚀 Welcome to RajeshwariTech!</h1>
            <p style="color: #e2e8f0; margin: 10px 0 0 0;">Thank you for your interest in ${customerData.service}</p>
          </div>
          
          <div style="background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
            <h2 style="color: #1e293b; margin: 0 0 20px 0;">Hi ${customerData.name}! 👋</h2>
            
            <p style="color: #475569; line-height: 1.6; margin-bottom: 20px;">
              Thank you for reaching out to us! We've received your enquiry about <strong>${customerData.service}</strong> and our team will get back to you within 24 hours.
            </p>
            
            <div style="background: #f1f5f9; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h3 style="color: #1e293b; margin: 0 0 15px 0;">📞 What happens next?</h3>
              <ul style="color: #475569; margin: 0; padding-left: 20px;">
                <li>Our team will review your requirements</li>
                <li>We'll contact you within 24 hours</li>
                <li>We'll provide a detailed proposal</li>
                <li>We'll schedule a consultation if needed</li>
              </ul>
            </div>
            
            <div style="background: #ecfdf5; padding: 20px; border-radius: 8px; border-left: 4px solid #10b981;">
              <h3 style="color: #065f46; margin: 0 0 10px 0;">💡 In the meantime...</h3>
              <p style="color: #047857; margin: 0;">Check out our <a href="https://rajeshwaritech.com/courses" style="color: #3b82f6;">courses</a> and <a href="https://rajeshwaritech.com/blogs" style="color: #3b82f6;">blog</a> for more information about our services.</p>
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 20px; color: #64748b; font-size: 12px;">
            <p>Best regards,<br>RajeshwariTech Team</p>
            <p>Visit: <a href="https://rajeshwaritech.com" style="color: #3b82f6;">rajeshwaritech.com</a></p>
          </div>
        </div>
      `,
    };

    const result = await transporter.sendMail(mailOptions);
    console.log('✅ Welcome email sent to customer:', result.messageId);
    return { success: true, messageId: result.messageId };
    
  } catch (error) {
    console.error('❌ Error sending welcome email:', error);
    return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
  }
};
